In [1]:
import os, sys
from pathlib import Path
script_dir = Path(os.path.dirname(os.path.abspath('')))
module_dir = str(script_dir)
sys.path.insert(0, module_dir + '/modules')
print(module_dir)

# import the rest of the modules
import numpy as np
import tensorflow as tf 
import matplotlib.pyplot as plt
import arch
import pandas as pd
import tensorflow_probability as tfp
import time  
import sim  

DTYPE = 'float32'

# define parameters for L63 system
dim = 4
sigma = 0.1

# define parameters for simlulation
n_particles = int(1e6)
n_subdivisions = 30
save_folder = '../data'
n_steps = 50
n_repeats = 10
dt = 0.1
r = 1.0

def mu_tf(X):
    x, y, x1, y1 = tf.split(X, dim, axis=-1)
    z = 4. * (x*x + y*y - 1.0)
    z1 = 4. * (x1*x1 + y1*y1 - 1.0)
    return tf.concat([-x*z, -y*z, -x1*z1, -y1*z1], axis=-1) 

mu_np = lambda X: mu_tf(X).numpy()

C:\Users\pinak\Documents\GitHub\sphere-fp


In [9]:
dim = 2
net = arch.LSTMForgetNet(50, 3, tf.float32, name="sphere{}D".format(dim))
net.load_weights('../data/{}D/{}'.format(dim, net.name)).expect_partial()
X = tf.random.uniform(shape=(10, dim))
net(*tf.split(X, dim, axis=-1))

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[0.04964349],
       [1.0038762 ],
       [0.8310665 ],
       [0.9627846 ],
       [1.0177319 ],
       [0.8403715 ],
       [0.9419359 ],
       [0.6031467 ],
       [1.006605  ],
       [0.2610526 ]], dtype=float32)>

In [3]:
X

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0.5408523 , 0.12475932, 0.7484211 , 0.9243221 , 0.83803344,
        0.48078668, 0.54013455, 0.56329274, 0.38482857, 0.61430395],
       [0.93250644, 0.4135965 , 0.75232875, 0.40419996, 0.07835102,
        0.00142956, 0.5295154 , 0.5227041 , 0.9729111 , 0.22750914],
       [0.48619998, 0.18832684, 0.3169012 , 0.5617664 , 0.45726466,
        0.57086086, 0.37055504, 0.8456882 , 0.5345105 , 0.99122167],
       [0.70990634, 0.01938367, 0.4384719 , 0.6978723 , 0.03823304,
        0.13845432, 0.55192435, 0.5889317 , 0.19967365, 0.9672669 ],
       [0.33871293, 0.53476465, 0.71716857, 0.11087835, 0.470541  ,
        0.7294009 , 0.22352266, 0.5304284 , 0.61900854, 0.8616674 ],
       [0.1819992 , 0.7636001 , 0.04163992, 0.05641365, 0.5553353 ,
        0.7564646 , 0.2153157 , 0.50806105, 0.11592638, 0.5026915 ],
       [0.87450886, 0.7063681 , 0.30024874, 0.82204425, 0.30529332,
        0.9919658 , 0.22662759, 0.9583936 , 0.6110554 , 0.12